name: Fetch Upstream
on:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정
  workflow_dispatch:

jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4

      - name: Check if upstream remote exists
        run: |
          if ! git remote get-url upstream &>/dev/null; then
            echo "Adding upstream remote"
            git remote add upstream https://github.com/jis-kim/ps-rolling.git
          else
            echo "Upstream remote already exists"
          fi

      - name: Fetch upstream main
        run: git fetch upstream main

      - name: Merge upstream changes
        run: |
          git merge upstream/main || echo "::warning:: 병합 충돌 발생"

      - name: Push changes
        run: |
          git push origin main
