name: Fetch Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정
  workflow_dispatch:

jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if upstream remote exists
        run: |
          if ! git remote get-url upstream &>/dev/null; then
            echo "Adding upstream remote"
            git remote add upstream https://github.com/raphaelheinz/LeetHub-3.0.git
          else
            echo "Upstream remote already exists"
          fi

      - name: Fetch upstream main
        run: git fetch --all

      - name: git config
        run: |
          git config --global user.name "Jisu"
          git config --global user.email "hellojs242@gmail.com"

      - name: Merge upstream changes
        run: |
          git rebase upstream/main
      - name: Push changes
        run: |
          git push origin main -f
